###
GET http://localhost:9000/area HTTP/1.1
###
GET http://localhost:9000/area/5 HTTP/1.1
###
POST http://localhost:9000/area HTTP/1.1
Content-Type: application/json

{
  "Area_Num": 2,
  "Area_Nom": "2",
  "Area_Descr": "area de gallinas",
  "Area_Espec": "gallina",
  "Area_CA": 12,
  "Area_E": "Activo",
}
